name    'ghoneycutt-xinetd'
version '1.1.1'
source 'git://github.com/ghoneycutt/puppet-xinetd.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Puppet Labs now maintains this module. Use puppetlabs/xinetd'
description 'Manages xinetd'
project_page 'https://github.com/ghoneycutt/puppet-xinetd/'
